name: Build C++ EXE

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Find and Build the project
      run: |
        $proj = Get-ChildItem -Filter *.vcxproj -Recurse | Select-Object -First 1
        Write-Host "Found project: $($proj.FullName)"
        msbuild "$($proj.FullName)" /m /p:Configuration=Release /p:Platform=x64

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pubg-DESYNC-Ready-Cheat
        path: "**/*.exe"
